export const RECEIVE_LOCATION_LIST = "RECEIVE_LOCATION_LIST";
export const RECEIVE_DEVICE_LIST = "RECEIVE_DEVICE_LIST";
export const RECEIVE_VLAN_LIST = "RECEIVE_VLAN_LIST";
export const RECEIVE_NAT_LIST = "RECEIVE_NAT_LIST";
export const RECEIVE_RACK_LIST = "RECEIVE_RACK_LIST";
export const RECEIVE_SUBNET_LIST = "RECEIVE_SUBNET_LIST";
